// <auto-generated />
using System;
using IARA.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IARA.Persistence.Migrations
{
    [DbContext(typeof(IARADbContext))]
    partial class IARADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IARA.Persistence.Data.Entities.BatchLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__BatchLoc__3214EC07D580DB2D");

                    b.HasIndex(new[] { "BatchId" }, "IX_BatchLocations_BatchId");

                    b.ToTable("BatchLocations");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Catch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Catches__3214EC073BE14AF7");

                    b.HasIndex("SpeciesId");

                    b.HasIndex(new[] { "OperationId" }, "IX_Catches_OperationId");

                    b.ToTable("Catches");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.EngineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageFuelConsumption")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("FuelUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__EngineTy__3214EC07F3BAB40A");

                    b.HasIndex(new[] { "TypeName" }, "UQ__EngineTy__D4E7DFA885E27956")
                        .IsUnique();

                    b.ToTable("EngineTypes");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LandingId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__FishBatc__3214EC07A14E5831");

                    b.HasIndex("SpeciesId");

                    b.HasIndex(new[] { "BatchCode" }, "IX_FishBatches_BatchCode");

                    b.HasIndex(new[] { "LandingId" }, "IX_FishBatches_LandingId");

                    b.HasIndex(new[] { "BatchCode" }, "UQ__FishBatc__B22ADA8E3830D45A")
                        .IsUnique();

                    b.ToTable("FishBatches");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishSpecy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__FishSpec__3214EC07845DB5B2");

                    b.HasIndex(new[] { "SpeciesName" }, "UQ__FishSpec__304D4C0DADCFB3B4")
                        .IsUnique();

                    b.ToTable("FishSpecies");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingGear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GearTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("MeshSize")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__FishingG__3214EC070D3BD345");

                    b.HasIndex("GearTypeId");

                    b.ToTable("FishingGears");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingGearType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__FishingG__3214EC072E68112E");

                    b.HasIndex(new[] { "TypeName" }, "UQ__FishingG__D4E7DFA8723FC1DD")
                        .IsUnique();

                    b.ToTable("FishingGearTypes");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FishingGearId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__FishingO__3214EC075248B5A6");

                    b.HasIndex("FishingGearId");

                    b.HasIndex(new[] { "TripId" }, "IX_FishingOps_TripId");

                    b.ToTable("FishingOperations");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingPermit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("PermitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date");

                    b.Property<int>("VesselId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__FishingP__3214EC0761E55F54");

                    b.HasIndex(new[] { "ValidUntil" }, "IX_FishingPermits_ValidUntil");

                    b.HasIndex(new[] { "VesselId" }, "IX_FishingPermits_VesselId");

                    b.HasIndex(new[] { "PermitNumber" }, "UQ__FishingP__DA3C94EED997A6A2")
                        .IsUnique();

                    b.ToTable("FishingPermits");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrivalDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArrivalPort")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeparturePort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("DurationHours")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(17, 6)")
                        .HasComputedColumnSql("(datediff(minute,[DepartureDateTime],isnull([ArrivalDateTime],sysdatetime()))/(60.0))", false);

                    b.Property<int>("PermitId")
                        .HasColumnType("int");

                    b.Property<int>("VesselId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__FishingT__3214EC07E117A50E");

                    b.HasIndex("PermitId");

                    b.HasIndex(new[] { "DepartureDateTime" }, "IX_FishingTrips_DepartureDateTime");

                    b.HasIndex(new[] { "VesselId" }, "IX_FishingTrips_VesselId");

                    b.ToTable("FishingTrips");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InspectionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("InspectorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("bit");

                    b.Property<int?>("TicketPurchaseId")
                        .HasColumnType("int");

                    b.Property<int?>("VesselId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Inspecti__3214EC07555A727C");

                    b.HasIndex("BatchId");

                    b.HasIndex("TicketPurchaseId");

                    b.HasIndex("VesselId");

                    b.HasIndex(new[] { "InspectionDateTime" }, "IX_Inspections_DateTime");

                    b.HasIndex(new[] { "InspectorId" }, "IX_Inspections_InspectorId");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Inspector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Inspecto__3214EC071830EEF4");

                    b.HasIndex(new[] { "PersonId" }, "UQ__Inspecto__AA2FFBE4708C57E8")
                        .IsUnique();

                    b.HasIndex(new[] { "BadgeNumber" }, "UQ__Inspecto__D110FD567045C85D")
                        .IsUnique();

                    b.ToTable("Inspectors");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Landing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LandingDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Landings__3214EC07C0CFF55A");

                    b.HasIndex(new[] { "TripId" }, "IX_Landings_TripId");

                    b.ToTable("Landings");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EGN")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Persons__3214EC07AF20FDAD");

                    b.HasIndex(new[] { "EGN" }, "IX_Persons_EGN");

                    b.HasIndex(new[] { "LastName", "FirstName" }, "IX_Persons_LastName");

                    b.HasIndex(new[] { "EGN" }, "UQ__Persons__C1902746ECAE8216")
                        .IsUnique()
                        .HasFilter("[EGN] IS NOT NULL");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.RecreationalCatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CatchDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("TicketPurchaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Recreati__3214EC0763B75942");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("TicketPurchaseId");

                    b.HasIndex(new[] { "CatchDateTime" }, "IX_RecCatches_CatchDateTime");

                    b.HasIndex(new[] { "PersonId" }, "IX_RecCatches_PersonId");

                    b.ToTable("RecreationalCatches");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.TELKDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DecisionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__TELKDeci__3214EC07FDF32121");

                    b.HasIndex(new[] { "PersonId" }, "IX_TELK_PersonId");

                    b.HasIndex(new[] { "DecisionNumber" }, "UQ__TELKDeci__BB11758214FDB233")
                        .IsUnique();

                    b.ToTable("TELKDecisions");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.TicketPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePaid")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<DateOnly>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<int?>("TELKDecisionId")
                        .HasColumnType("int");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__TicketPu__3214EC0714114533");

                    b.HasIndex("TELKDecisionId");

                    b.HasIndex("TicketTypeId");

                    b.HasIndex(new[] { "PersonId" }, "IX_TicketPurchases_PersonId");

                    b.HasIndex(new[] { "TicketNumber" }, "UQ__TicketPu__CBED06DA55E2E47D")
                        .IsUnique();

                    b.ToTable("TicketPurchases");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFreeForDisabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("PriceAdult")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("PricePensioner")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("PriceUnder14")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TicketTy__3214EC077D6B8F05");

                    b.HasIndex(new[] { "TypeName" }, "UQ__TicketTy__D4E7DFA8A7EDAD5F")
                        .IsUnique();

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PersonId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CallSign")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CaptainId")
                        .HasColumnType("int");

                    b.Property<decimal>("Draft")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal>("EnginePower")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("EngineTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrossTonnage")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("InternationalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Vessels__3214EC07203BA2D7");

                    b.HasIndex("CaptainId");

                    b.HasIndex("EngineTypeId");

                    b.HasIndex(new[] { "InternationalNumber" }, "IX_Vessels_InternationalNumber");

                    b.HasIndex(new[] { "OwnerId" }, "IX_Vessels_Owner");

                    b.HasIndex(new[] { "InternationalNumber" }, "UQ__Vessels__0D0EED16EF482DAE")
                        .IsUnique();

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Violation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("InspectionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Violatio__3214EC07469064E3");

                    b.HasIndex(new[] { "InspectionId" }, "IX_Violations_InspectionId");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PermitFishingGear", b =>
                {
                    b.Property<int>("PermitId")
                        .HasColumnType("int");

                    b.Property<int>("FishingGearId")
                        .HasColumnType("int");

                    b.HasKey("PermitId", "FishingGearId")
                        .HasName("PK__PermitFi__7E72B374CA7502B2");

                    b.HasIndex("FishingGearId");

                    b.ToTable("PermitFishingGears", (string)null);
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.BatchLocation", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.FishBatch", "Batch")
                        .WithMany("BatchLocations")
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("FK_BatchLocations_Batch");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Catch", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.FishingOperation", "Operation")
                        .WithMany("Catches")
                        .HasForeignKey("OperationId")
                        .IsRequired()
                        .HasConstraintName("FK_Catches_Operation");

                    b.HasOne("IARA.Persistence.Data.Entities.FishSpecy", "Species")
                        .WithMany("Catches")
                        .HasForeignKey("SpeciesId")
                        .IsRequired()
                        .HasConstraintName("FK_Catches_Species");

                    b.Navigation("Operation");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishBatch", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.Landing", "Landing")
                        .WithMany("FishBatches")
                        .HasForeignKey("LandingId")
                        .IsRequired()
                        .HasConstraintName("FK_FishBatches_Landing");

                    b.HasOne("IARA.Persistence.Data.Entities.FishSpecy", "Species")
                        .WithMany("FishBatches")
                        .HasForeignKey("SpeciesId")
                        .IsRequired()
                        .HasConstraintName("FK_FishBatches_Species");

                    b.Navigation("Landing");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingGear", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.FishingGearType", "GearType")
                        .WithMany("FishingGears")
                        .HasForeignKey("GearTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_FishingGears_Type");

                    b.Navigation("GearType");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingOperation", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.FishingGear", "FishingGear")
                        .WithMany("FishingOperations")
                        .HasForeignKey("FishingGearId")
                        .IsRequired()
                        .HasConstraintName("FK_FishingOps_Gear");

                    b.HasOne("IARA.Persistence.Data.Entities.FishingTrip", "Trip")
                        .WithMany("FishingOperations")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK_FishingOps_Trip");

                    b.Navigation("FishingGear");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingPermit", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.Vessel", "Vessel")
                        .WithMany("FishingPermits")
                        .HasForeignKey("VesselId")
                        .IsRequired()
                        .HasConstraintName("FK_FishingPermits_Vessel");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingTrip", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.FishingPermit", "Permit")
                        .WithMany("FishingTrips")
                        .HasForeignKey("PermitId")
                        .IsRequired()
                        .HasConstraintName("FK_FishingTrips_Permit");

                    b.HasOne("IARA.Persistence.Data.Entities.Vessel", "Vessel")
                        .WithMany("FishingTrips")
                        .HasForeignKey("VesselId")
                        .IsRequired()
                        .HasConstraintName("FK_FishingTrips_Vessel");

                    b.Navigation("Permit");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Inspection", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.FishBatch", "Batch")
                        .WithMany("Inspections")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK_Inspections_Batch");

                    b.HasOne("IARA.Persistence.Data.Entities.Inspector", "Inspector")
                        .WithMany("Inspections")
                        .HasForeignKey("InspectorId")
                        .IsRequired()
                        .HasConstraintName("FK_Inspections_Inspector");

                    b.HasOne("IARA.Persistence.Data.Entities.TicketPurchase", "TicketPurchase")
                        .WithMany("Inspections")
                        .HasForeignKey("TicketPurchaseId")
                        .HasConstraintName("FK_Inspections_Ticket");

                    b.HasOne("IARA.Persistence.Data.Entities.Vessel", "Vessel")
                        .WithMany("Inspections")
                        .HasForeignKey("VesselId")
                        .HasConstraintName("FK_Inspections_Vessel");

                    b.Navigation("Batch");

                    b.Navigation("Inspector");

                    b.Navigation("TicketPurchase");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Inspector", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.Person", "Person")
                        .WithOne("Inspector")
                        .HasForeignKey("IARA.Persistence.Data.Entities.Inspector", "PersonId")
                        .IsRequired()
                        .HasConstraintName("FK_Inspectors_Person");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Landing", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.FishingTrip", "Trip")
                        .WithMany("Landings")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK_Landings_Trip");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.RecreationalCatch", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.Person", "Person")
                        .WithMany("RecreationalCatches")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("FK_RecCatches_Person");

                    b.HasOne("IARA.Persistence.Data.Entities.FishSpecy", "Species")
                        .WithMany("RecreationalCatches")
                        .HasForeignKey("SpeciesId")
                        .IsRequired()
                        .HasConstraintName("FK_RecCatches_Species");

                    b.HasOne("IARA.Persistence.Data.Entities.TicketPurchase", "TicketPurchase")
                        .WithMany("RecreationalCatches")
                        .HasForeignKey("TicketPurchaseId")
                        .IsRequired()
                        .HasConstraintName("FK_RecCatches_Ticket");

                    b.Navigation("Person");

                    b.Navigation("Species");

                    b.Navigation("TicketPurchase");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.TELKDecision", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.Person", "Person")
                        .WithMany("TELKDecisions")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("FK_TELK_Person");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.TicketPurchase", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.Person", "Person")
                        .WithMany("TicketPurchases")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("FK_TicketPurchases_Person");

                    b.HasOne("IARA.Persistence.Data.Entities.TELKDecision", "TELKDecision")
                        .WithMany("TicketPurchases")
                        .HasForeignKey("TELKDecisionId")
                        .HasConstraintName("FK_TicketPurchases_TELK");

                    b.HasOne("IARA.Persistence.Data.Entities.TicketType", "TicketType")
                        .WithMany("TicketPurchases")
                        .HasForeignKey("TicketTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_TicketPurchases_Type");

                    b.Navigation("Person");

                    b.Navigation("TELKDecision");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.User", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Vessel", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.Person", "Captain")
                        .WithMany("VesselCaptains")
                        .HasForeignKey("CaptainId")
                        .IsRequired()
                        .HasConstraintName("FK_Vessels_Captain");

                    b.HasOne("IARA.Persistence.Data.Entities.EngineType", "EngineType")
                        .WithMany("Vessels")
                        .HasForeignKey("EngineTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Vessels_EngineType");

                    b.HasOne("IARA.Persistence.Data.Entities.Person", "Owner")
                        .WithMany("VesselOwners")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Vessels_Owner");

                    b.Navigation("Captain");

                    b.Navigation("EngineType");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Violation", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.Inspection", "Inspection")
                        .WithMany("Violations")
                        .HasForeignKey("InspectionId")
                        .IsRequired()
                        .HasConstraintName("FK_Violations_Inspection");

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IARA.Persistence.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermitFishingGear", b =>
                {
                    b.HasOne("IARA.Persistence.Data.Entities.FishingGear", null)
                        .WithMany()
                        .HasForeignKey("FishingGearId")
                        .IsRequired()
                        .HasConstraintName("FK_PermitGears_Gear");

                    b.HasOne("IARA.Persistence.Data.Entities.FishingPermit", null)
                        .WithMany()
                        .HasForeignKey("PermitId")
                        .IsRequired()
                        .HasConstraintName("FK_PermitGears_Permit");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.EngineType", b =>
                {
                    b.Navigation("Vessels");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishBatch", b =>
                {
                    b.Navigation("BatchLocations");

                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishSpecy", b =>
                {
                    b.Navigation("Catches");

                    b.Navigation("FishBatches");

                    b.Navigation("RecreationalCatches");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingGear", b =>
                {
                    b.Navigation("FishingOperations");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingGearType", b =>
                {
                    b.Navigation("FishingGears");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingOperation", b =>
                {
                    b.Navigation("Catches");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingPermit", b =>
                {
                    b.Navigation("FishingTrips");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.FishingTrip", b =>
                {
                    b.Navigation("FishingOperations");

                    b.Navigation("Landings");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Inspection", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Inspector", b =>
                {
                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Landing", b =>
                {
                    b.Navigation("FishBatches");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Person", b =>
                {
                    b.Navigation("Inspector");

                    b.Navigation("RecreationalCatches");

                    b.Navigation("TELKDecisions");

                    b.Navigation("TicketPurchases");

                    b.Navigation("VesselCaptains");

                    b.Navigation("VesselOwners");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.TELKDecision", b =>
                {
                    b.Navigation("TicketPurchases");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.TicketPurchase", b =>
                {
                    b.Navigation("Inspections");

                    b.Navigation("RecreationalCatches");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.TicketType", b =>
                {
                    b.Navigation("TicketPurchases");
                });

            modelBuilder.Entity("IARA.Persistence.Data.Entities.Vessel", b =>
                {
                    b.Navigation("FishingPermits");

                    b.Navigation("FishingTrips");

                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
